.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SMEMSTAT 8 "August 30, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
smemstat \- report memory usage with shared memory divided proportionally
.br

.SH SYNOPSIS
.B smemstat
[options]
.RI [ delay " [" count ]]
.br

.SH DESCRIPTION
smemstat reports the physical memory usage taking into consideration shared
memory.  

Swap reports memory that is swapped out to disk. Unshared memory is reported
as USS (Unique Set Size).  Unshared memory including the proportion of shared
memory is reported as the PSS (Proportional Set Size).  The non-swapped
physical memory is reported as the RSS (Resident Set Size).

Running with root privilege will report all user space processes, otherwise
running without will just report the current user's processes.

If a delay and count are not specified, a snapshot of the current memory used by
the user's processes is report.

If a delay in seconds is specified, smemstat will periodically show any per-process changes in
memory; the interval being the specified delay.  This will run indefinitely until 
a SIGINT is caught.   Specifying count will repeat the periodic output count number of times.

.SH OPTIONS
smemstat options are as follow:
.TP
.B \-a
show memory size change with up arrow \[u2191] (increase) and down arrow \[u2193] (decrease)
.TP
.B \-c
get command information from processes comm field
.TP
.B \-d
strip directory basename off command information
.TP
.B \-g
report memory in gigabytes
.TP
.B \-h
show help
.TP
.B \-k
report memory in kilobytes
.TP
.B \-l
show long (full) command information
.TP
.B \-m
report memory in megabytes
.TP
.B \-o file
output data into a JSON formatted file
.TP
.B \-p proclist
specify a comma separated list of processes to monitor. The
process list may contain one or more PIDs or process names.
.TP
.B \-q 
run quietly, only really makes sense with \-o option
.TP
.B \-s
show short command information
.TP
.B \-t
top mode, show top changes of memory
.TP
.B \-T
top mode, show top consumers of memory
.PP
When running in 'top mode', pressing 'q' will quit, 'a' toggles the memory
change arrow, 't' toggles the top consumers of memory view.
.SH SEE ALSO
.BR cpustat (8),
.BR eventstat (8),
.BR forkstat (8),
.BR top (1),
.BR vmstat (8)
.SH AUTHOR
smemstat was written by Colin Ian King <colin.i.king@gmail.com>
.PP
This manual page was written by Colin Ian King <colin.i.king@gmail.com>,
for the Ubuntu project (but may be used by others).
.SH COPYRIGHT
Copyright \(co 2014-2021 Canonical Ltd, Copyright \(co 2021-2202 Colin Ian King.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
