name: smemstat
version: 0.01.18-20180405-112-5022076
summary: memory usage monitoring tool
description: smemstat reports the physical memory usage taking into consideration shared memory.  The tool can either report a current snapshot of memory usage or periodically dump out any changes in memory.
confinement: strict
type: app
grade: devel

parts:
    smemstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/smemstat
        build-packages:
            - gcc
            - make
apps:
    smemstat:
        command: usr/bin/smemstat
        plugs:
          - system-observe
          - system-trace
          - process-control

