name: smemstat
summary: memory usage monitoring tool
description: smemstat reports the physical memory usage taking into consideration shared memory.  The tool can either report a current snapshot of memory usage or periodically dump out any changes in memory.
confinement: strict
grade: stable
assumes: [snapd2.45]
base: core18
adopt-info: smemstat

architectures:
    - build-on: s390x
    - build-on: ppc64el
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

parts:
    smemstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/smemstat
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"
        build-packages:
            - gcc
            - make
            - libncurses-dev
            - libncursesw5-dev
        stage-packages:
            - libncurses-dev
            - libncursesw5-dev

apps:
    smemstat:
        command: usr/bin/smemstat
        plugs:
          - system-observe
          - system-trace
          - process-control

