name: smemstat
version: 0.02.00-20180628-126-2570293
summary: memory usage monitoring tool
description: smemstat reports the physical memory usage taking into consideration shared memory.  The tool can either report a current snapshot of memory usage or periodically dump out any changes in memory.
confinement: strict
type: app
grade: stable

parts:
    smemstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/smemstat
        build-packages:
            - gcc
            - make
            - libncurses-dev
            - libncursesw5-dev
        stage-packages:
            - libncurses-dev
            - libncursesw5-dev
apps:
    smemstat:
        command: usr/bin/smemstat
        plugs:
          - system-observe
          - system-trace
          - process-control

